<a href="https://colab.research.google.com/github/hkhong72/big_data/blob/main/221006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

장문석
01097280948
jejutour@daum.net
https://ehpub.co.kr
youtube : 언제나휴일-프로그래머

10월 6~18(7일)
Python
빅데이터
수집/분석/시각화  matlotlib
텍스트마이닝 -> 원하는 키워드만 뽑아냄 ex) 기사내용중 원하는 단어만 채굴
강의에 사용한 소스 코드
https://github.com/ehpub/bit2210_bigdata

colab

In [ ]:
ls = [[1,2,3,4],[3,4,5],[2,3],[1],1,2,'Hello']
print(ls)

In [ ]:
#numpy 모듈을 사용하기 위한 import문
import numpy as np
ls = [1,2,3,4,5]
arr = np.array(ls)
print(arr)
print(type(arr)) #다차원 배열을 표현하는 타입이 ndarray


In [ ]:
ls1 = [1,2,3]
ls2 = [4,7,2]
ls3 = ls1+ls2
print(ls3) # 파이썬 리스트의 합은 concat

In [ ]:
arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr3 = arr1+arr2
print(arr3)

In [ ]:
ls = [1,2,3]
ls2=ls*3
print(ls2) #리스트 *숫자 는 원소를 반복해서 나열

In [ ]:
arr =np.array(ls)
arr2 = arr*3
print(arr2) #numpy의 ndarray *정수는 행렬*정수 연산을 수행

In [ ]:
%%time
arr = np.arange(100000)

In [ ]:
%%time
ls = list(range(100000))

$$time을 마킹하면 수행시간을 측정해준다.

In [ ]:
arr = np.random.randn(2,3)
print(arr)

In [ ]:
arr * 3 #여기서 arr의 기존 값은 바뀌지않음. arr*3의 값을 반환해준것이다.

In [ ]:
arr.shape #구조 확인 !!

In [ ]:
arr.ndim #차원 확인 !!

In [ ]:
arr.dtype #원소 타입 확인

In [ ]:
arr = np.array([1,2,3])
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3,4.2]) #실수가 하나라도 있을 시 실수형으로 자동캐스팅된것을 확인가능, numpy의 원소는 모두 같은 타입을 가지고있음
print(arr)
print(arr.dtype)
print(type(arr[0]))

In [ ]:
arr = np.array([1,2,3,4.2,'a'])  # 모두 문자열로 변환되는 것을 확인
print(arr)
print(arr.dtype)
print(type(arr[0]))

In [ ]:
ls = ([1,2,3],[2,5,6])
arr = np.array(ls) #리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

In [ ]:
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

In [ ]:
arr = np.zeros((3,6))
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

In [ ]:
arr = np.ones((3,6))
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
구조 :  (3, 6)
차원 :  2
원소 형식 :  float64


In [ ]:
arr = np.arange(3,20,4)
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

In [ ]:
arr = np.array([1,2,4.2], dtype=np.int32) # dtype옵션을 통해서 요소타입을 전부 캐스팅가능
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("============")
arr2 = arr*arr
print(arr2)

In [ ]:
arr2 = arr-arr
print(arr2)

In [ ]:
arr2 = 1/arr
print(arr2)

In [ ]:
arr2 = arr**0.5
print(arr2)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,0,2])
filter = arr1>arr2
print(filter)

In [ ]:
arr = np.arange(1000)
print(arr[5:8])

In [ ]:
print(arr[:8])

In [ ]:
print(arr[995:])

In [ ]:
print(arr[-5:])

In [ ]:
arr = np.zeros(30)
print(arr)

In [ ]:
arr[5:8]=7 #원하는 영역을 체인지 가능
print(arr)

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[0][2])
print(arr[0,2])

In [ ]:
#소스 배열을 가지고 간단한 실험을 하기 위해서 복사하여 사용하기
cp_arr = arr.copy()  # 복사했기때문에 arr과 cp_arr은 다른 두개의 내용만같은 개체를 참조함 -> 참조할 새 개체가 생성됨
print(cp_arr)
cp_arr = cp_arr * 2 #원본arr은 .copy했기 때문에 바뀌지않음
print(cp_arr)
print(arr)

In [ ]:
cp_arr = arr # 원본 arr의 요소도 변함 -> arr과 cp_arr은 하나의 같은 개체를 참조함
print(cp_arr)
cp_arr[0][1] = 8
print(cp_arr)
print(arr)

In [ ]:
arr = np.array([1,2,3])
filter = arr>=2
print(filter)

In [ ]:
res = arr[filter]
print(res)

In [ ]:
arr = np.arange(96)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)

In [ ]:
arr2 = arr.reshape((6,16)) #arr2=arr.reshpae((7,13)) #구조 변경할 때 요소의 개수가 같을때만 구조 변경가능
print("구조 : ",arr2.shape)
print("차원 : ",arr2.ndim)

In [ ]:
arr2 = arr.reshape((6,-1)) #구조 변경 요청할 때 하나의 차원은 -1로 표현 가능(알아서 계산해줌)
print("구조 : ",arr2.shape)
print("차원 : ",arr2.ndim)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]]) 
arr2 = arr.T # 전치행렬 -> 행렬을 90도 회전한것이라고 이해하기 / 로우와 컬럼이 바뀜 # arr.T 와 arr.transpose()는 같은 결과(전치행렬)를 반환
print(arr)
print("===")
print(arr2)

In [ ]:
arr = np.arange(10)
print(arr)

In [ ]:
arr2 = np.sqrt(arr) # 루트씌움
print(arr2)
print(arr)

In [ ]:
arr1 = np.random.randn(2,3)
print(arr1)
print("===")
arr2 = np.random.randn(2,3)
print(arr2)
arr3 = np.maximum(arr1, arr2)
print(arr3)

In [ ]:
#잠시 파이썬 기본 문법 - 리스트 컴프리헨션
xs = [x*x+2*x+3 for x in range(1, 10)] #리스트 컴프리헨션
print(xs)

In [ ]:
xs=[]
for x in range(1,10):
  xs.append(x*x+2*x+3)
print(xs)

In [ ]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

ls1=[1,2,3] # zip 이용 예
ls2=['가','나','다']
for e1, e2 in zip(ls1, ls2):
  print(e1,e2)


In [ ]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result)

In [ ]:
result=[]
for x,y,c in zip(xarr, yarr, cond):
  if c:
    result.append(x)
  else:
    result.append(y)
print(result)

In [ ]:
result = np.where(cond, xarr, yarr)
print(result)

In [ ]:
heights = np.random.normal(172.4, 5, 100) #평균 172.4 표준편차 5인 표본을 1000개 생성
print(heights)

In [ ]:
print("평균 : ", heights.mean()) #print("평균 : ",np.mean(heights))
print("합계 : ", heights.sum()) #print("평균 : ",np.sum(heights))

In [ ]:
h2 = heights.reshape(20,-1)
print("구조 : ",h2.shape)

In [ ]:
print("평균(축1) : ", h2.mean(axis=1)) #로우 별 평균
print("평균(축0) : ", h2.mean(axis=0)) #컬럼 별 평균

In [ ]:
print("합계(축1) : ", h2.sum(axis=1)) #로우 별 합계
print("합계(축0) : ", h2.sum(axis=0)) #컬럼 별 합계

In [ ]:
print("분산 : ", h2.var()) 
print("표준편차 : ", h2.std())

In [ ]:
print("최솟값 : ", h2.min()) 
print("최댓값 : ", h2.max())

In [ ]:
print("최솟값이 있는 위치 : ", heights.argmin()) 
print("최댓값이 있는 위치 : ", heights.argmax())
print(heights[heights.argmin()],heights[heights.argmax()])

In [ ]:
arr = np.array([1,2,4,2,7])
print("누적 합계 : ",arr.cumsum())
print("누적 곱 : ",arr.cumprod())

In [ ]:
arr.sort()
print(arr)

In [ ]:
ua = np.unique(arr) # unique 는중복된 원소를 제거하고 남은 원소를 정렬된 형태로 반환하는 함수
print(ua)

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,3],[1,2],[4,5]])
re = x.dot(y)
print(x)
print("===")
print(y)
print("===")
print(re)

**난수**

In [ ]:
for _ in range(10): # _ 는 변수를 설정하지 않겠다 라는 뜻이다.
  print(np.random.uniform(-2,3)) #uniform(a,b) a~b사이의 랜덤한 실수 반환

In [ ]:
for _ in range(20): 
  print(np.random.randint(1,5),end=' ')
print()

In [ ]:
volan = [1,7,2,8,9]
for _ in range(20):
  print(np.random.choice(volan),end=' ')
print()

In [ ]:
num = np.random.seed(100) # ??
print(num)

평균, 중간값, 사분위값, 최빈값, 분산, 표준편차, 공분산, 상관계수

In [ ]:
import numpy as np

In [ ]:
heights = np.random.normal(161.4, 4, 200) #평균 161.4 표준편차 4, 표본 200개 생성
print(heights)

소개 what is numpy?
https://numpy.org/doc/stable/user/whatisnumpy.html