<a href="https://colab.research.google.com/github/hkhong72/big_data/blob/main/221016%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

장문석 01097280948 jejutour@daum.net https://ehpub.co.kr youtube : 언제나휴일-프로그래머

10월 6~18(7일) Python 빅데이터 수집/분석/시각화 matlotlib 텍스트마이닝 -> 원하는 키워드만 뽑아냄 ex) 기사내용중 원하는 단어만 채굴 강의에 사용한 소스 코드 https://github.com/ehpub/bit2210_bigdata

colab

In [1]:
ls = [[1,2,3,4],[3,4,5],[2,3],[1],1,2,'Hello']
print(ls)

[[1, 2, 3, 4], [3, 4, 5], [2, 3], [1], 1, 2, 'Hello']


In [2]:
#numpy 모듈을 사용하기 위한 import문
import numpy as np
ls = [1,2,3,4,5]
arr = np.array(ls)
print(arr)
print(type(arr)) #다차원 배열을 표현하는 타입이 ndarray
ls1 = [1,2,3]
ls2 = [4,7,2]
ls3 = ls1+ls2
print(ls3) # 파이썬 리스트의 합은 concat

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 7, 2]


In [3]:
arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr3 = arr1+arr2
print(arr3)
ls = [1,2,3]
ls2=ls*3
print(ls2) #리스트 *숫자 는 원소를 반복해서 나열
arr =np.array(ls)
arr2 = arr*3
print(arr2) #numpy의 ndarray *정수는 행렬*정수 연산을 수행
%%time
arr = np.arange(100000)
%%time
ls = list(range(100000))

[5 9 5]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


UsageError: Line magic function `%%time` not found.


$$time을 마킹하면 수행시간을 측정해준다.

In [4]:
arr = np.random.randn(2,3)
print(arr)
arr * 3 #여기서 arr의 기존 값은 바뀌지않음. arr*3의 값을 반환해준것이다.
arr.shape #구조 확인 !!
arr.ndim #차원 확인 !!
arr.dtype #원소 타입 확인
arr = np.array([1,2,3])
print(arr)
print(arr.dtype)
arr = np.array([1,2,3,4.2]) #실수가 하나라도 있을 시 실수형으로 자동캐스팅된것을 확인가능, numpy의 원소는 모두 같은 타입을 가지고있음
print(arr)
print(arr.dtype)
print(type(arr[0]))
arr = np.array([1,2,3,4.2,'a'])  # 모두 문자열로 변환되는 것을 확인
print(arr)
print(arr.dtype)
print(type(arr[0]))
ls = ([1,2,3],[2,5,6])
arr = np.array(ls) #리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)
arr = np.zeros((3,6))
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)
arr = np.ones((3,6))
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

[[ 0.20018612 -0.28204685 -0.66630102]
 [ 0.55988699 -2.26707162  0.49656689]]
[1 2 3]
int64
[1.  2.  3.  4.2]
float64
<class 'numpy.float64'>
['1' '2' '3' '4.2' 'a']
<U32
<class 'numpy.str_'>
[[1 2 3]
 [2 5 6]]
<class 'numpy.ndarray'>
구조 :  (2, 3)
차원 :  2
원소 형식 :  int64
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
구조 :  (3, 6)
차원 :  2
원소 형식 :  float64
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
구조 :  (3, 6)
차원 :  2
원소 형식 :  float64


In [5]:
arr = np.arange(3,20,4)
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)
arr = np.array([1,2,4.2], dtype=np.int32) # dtype옵션을 통해서 요소타입을 전부 캐스팅가능
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("============")
arr2 = arr*arr
print(arr2)
arr2 = arr-arr
print(arr2)
arr2 = 1/arr
print(arr2)
arr2 = arr**0.5
print(arr2)
arr1 = np.array([1,2,3])
arr2 = np.array([4,0,2])
filter = arr1>arr2
print(filter)
arr = np.arange(1000)
print(arr[5:8])
print(arr[:8])
print(arr[995:])
print(arr[-5:])
arr = np.zeros(30)
print(arr)
arr[5:8]=7 #원하는 영역을 체인지 가능
print(arr)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[0][2])
print(arr[0,2])
#소스 배열을 가지고 간단한 실험을 하기 위해서 복사하여 사용하기
cp_arr = arr.copy()  # 복사했기때문에 arr과 cp_arr은 다른 두개의 내용만같은 개체를 참조함 -> 참조할 새 개체가 생성됨
print(cp_arr)
cp_arr = cp_arr * 2 #원본arr은 .copy했기 때문에 바뀌지않음
print(cp_arr)
print(arr)
cp_arr = arr # 원본 arr의 요소도 변함 -> arr과 cp_arr은 하나의 같은 개체를 참조함
print(cp_arr)
cp_arr[0][1] = 8
print(cp_arr)
print(arr)
arr = np.array([1,2,3])
filter = arr>=2
print(filter)
res = arr[filter]
print(res)
arr = np.arange(96)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
arr2 = arr.reshape((6,16)) #arr2=arr.reshpae((7,13)) #구조 변경할 때 요소의 개수가 같을때만 구조 변경가능
print("구조 : ",arr2.shape)
print("차원 : ",arr2.ndim)
arr2 = arr.reshape((6,-1)) #구조 변경 요청할 때 하나의 차원은 -1로 표현 가능(알아서 계산해줌)
print("구조 : ",arr2.shape)
print("차원 : ",arr2.ndim)
arr = np.array([[1,2,3],[4,5,6]]) 
arr2 = arr.T # 전치행렬 -> 행렬을 90도 회전한것이라고 이해하기 / 로우와 컬럼이 바뀜 # arr.T 와 arr.transpose()는 같은 결과(전치행렬)를 반환
print(arr)
print("===")
print(arr2)
arr = np.arange(10)
print(arr)
arr2 = np.sqrt(arr) # 루트씌움
print(arr2)
print(arr)
arr1 = np.random.randn(2,3)
print(arr1)
print("===")
arr2 = np.random.randn(2,3)
print(arr2)
arr3 = np.maximum(arr1, arr2)
print(arr3)
#잠시 파이썬 기본 문법 - 리스트 컴프리헨션
xs = [x*x+2*x+3 for x in range(1, 10)] #리스트 컴프리헨션
print(xs)
xs=[]
for x in range(1,10):
  xs.append(x*x+2*x+3)
print(xs)
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

ls1=[1,2,3] # zip 이용 예
ls2=['가','나','다']
for e1, e2 in zip(ls1, ls2):
  print(e1,e2)
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result)
result=[]
for x,y,c in zip(xarr, yarr, cond):
  if c:
    result.append(x)
  else:
    result.append(y)
print(result)
result = np.where(cond, xarr, yarr)
print(result)
heights = np.random.normal(172.4, 5, 100) #평균 172.4 표준편차 5인 표본을 1000개 생성
print(heights)
print("평균 : ", heights.mean()) #print("평균 : ",np.mean(heights))
print("합계 : ", heights.sum()) #print("평균 : ",np.sum(heights))
h2 = heights.reshape(20,-1)
print("구조 : ",h2.shape)
print("평균(축1) : ", h2.mean(axis=1)) #로우 별 평균
print("평균(축0) : ", h2.mean(axis=0)) #컬럼 별 평균
print("합계(축1) : ", h2.sum(axis=1)) #로우 별 합계
print("합계(축0) : ", h2.sum(axis=0)) #컬럼 별 합계
print("분산 : ", h2.var()) 
print("표준편차 : ", h2.std())
print("최솟값 : ", h2.min()) 
print("최댓값 : ", h2.max())
print("최솟값이 있는 위치 : ", heights.argmin()) 
print("최댓값이 있는 위치 : ", heights.argmax())
print(heights[heights.argmin()],heights[heights.argmax()])
arr = np.array([1,2,4,2,7])
print("누적 합계 : ",arr.cumsum())
print("누적 곱 : ",arr.cumprod())
arr.sort()
print(arr)
ua = np.unique(arr) # unique 는중복된 원소를 제거하고 남은 원소를 정렬된 형태로 반환하는 함수
print(ua)
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,3],[1,2],[4,5]])
re = x.dot(y)
print(x)
print("===")
print(y)
print("===")
print(re)

[ 3  7 11 15 19]
구조 :  (5,)
차원 :  1
원소 형식 :  int64
<class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'>
int32
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[False  True  True]
[5 6 7]
[0 1 2 3 4 5 6 7]
[995 996 997 998 999]
[995 996 997 998 999]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 7. 7. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[1 2 3]
[4 5 6]
[7 8 9]
3
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[False  True  True]
[2 3]
구조 :  (96,)
차원 :  1
구조 :  (6, 16)
차원 :  2
구조 :  (6, 16)
차원 :  2
[[1 2 3]
 [4 5 6]]
===
[[1 4]
 [2 5]
 [3 6]]
[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421

난수

In [7]:
for _ in range(10): # _ 는 변수를 설정하지 않겠다 라는 뜻이다.
  print(np.random.uniform(-2,3)) #uniform(a,b) a~b사이의 랜덤한 실수 반환
for _ in range(20): 
  print(np.random.randint(1,5),end=' ')
print()
volan = [1,7,2,8,9]
for _ in range(20):
  print(np.random.choice(volan),end=' ')
print()
num = np.random.seed(100) # ??
print(num)
# 평균, 중간값, 사분위값, 최빈값, 분산, 표준편차, 공분산, 상관계수

import numpy as np
heights = np.random.normal(161.4, 4, 200) #평균 161.4 표준편차 4, 표본 200개 생성
print(heights)

0.7170247089548272
-0.6081530745310193
0.12258795374566533
2.2238806615995186
-1.9764057190451372
-1.392154396084429
1.3537454236338933
2.1292637755252386
-1.316467051575235
0.8754666471362498
1 4 1 3 1 4 2 2 3 3 4 1 1 4 2 2 2 4 1 1 
8 8 8 7 7 8 1 2 7 7 8 2 8 1 7 1 9 2 1 1 
None
[154.40093811 162.77072161 166.01214321 160.39025585 165.32528315
 163.45687537 162.28471868 157.11982668 160.64201668 162.42000578
 159.56789206 163.14065395 159.0656198  164.66738829 164.09088322
 160.98235543 159.27487849 165.51893074 159.64745751 156.92672701
 167.87592664 167.5664207  160.39248344 158.03025705 162.13807476
 165.1483288  164.32400138 166.8462245  160.09504776 161.62270406
 162.28959843 155.62713202 158.37459078 164.66581604 164.40177905
 159.57621229 166.15848907 154.63753269 155.9744038  156.47026194
 159.22224335 158.72731305 161.42925825 158.94824506 166.5989923
 154.46761751 157.4667596  162.83003101 154.94568599 167.28285547
 156.64792961 159.20101523 157.63981535 158.08827054 161.8354

# 소개 what is numpy? https://numpy.org/doc/stable/user/whatisnumpy.html